spring:
  application:
    name: smartypants
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          must-revalidate: true
          max-age: 0
server:
  port: 8086
ollama:
  url: https://gpt.jdelfino.com/ollama/api/generate
  model: gemma3n:latest
